In [7]:
# pip install textblob
# !pip install tabula-py

In [8]:
import pandas as pd
from textblob import TextBlob
from tabula import read_pdf

In [12]:
df_students = pd.read_csv('students.csv')
df_courses = pd.read_csv('courses.csv')

In [18]:
df_students

  StudentID       FullName                    Email CourseID    JoinDate
0      S001   James Mwangi   james.mwangi@email.com     C001  2024-02-10
1      S002    Faith Njeri    faith.njeri@email.com     C002  2024-03-12
2      S003   Kevin Otieno   kevin.otieno@email.com     C001  2024-03-20
3      S004  Susan Achieng  susan.achieng@email.com     C003  2024-04-01
4      S005    Brian Kamau    brian.kamau@email.com     C002  2024-04-15
5      S006   Lucy Wanjiru   lucy.wanjiru@email.com     C004  2024-05-02
6      S007   David Kiptoo   david.kiptoo@email.com     C001  2024-06-10
7      S008   Naomi Wambui   naomi.wambui@email.com     C003  2024-06-25
8      S009  Peter Njoroge  peter.njoroge@email.com     C004  2024-07-01
9      S010  Esther Chebet  esther.chebet@email.com     C002  2024-07-18

In [5]:
df_courses

  CourseID            CourseName  Department  DurationMonths     Fee
0     C001  Software Engineering  Technology              12  150000
1     C002          Data Science  Technology              10  130000
2     C003     Digital Marketing    Business               6   80000
3     C004        Graphic Design      Design               8  100000

In [19]:
student_courses = pd.merge(df_students, df_courses, on = 'CourseID', how = 'inner')
student_courses

,StudentID,FullName,Email,CourseID,JoinDate,CourseName,Department,DurationMonths,Fee
0,S001,James Mwangi,james.mwangi@email.com,C001,2024-02-10,Software Engineering,Technology,12,150000
1,S002,Faith Njeri,faith.njeri@email.com,C002,2024-03-12,Data Science,Technology,10,130000
2,S003,Kevin Otieno,kevin.otieno@email.com,C001,2024-03-20,Software Engineering,Technology,12,150000
3,S004,Susan Achieng,susan.achieng@email.com,C003,2024-04-01,Digital Marketing,Business,6,80000
4,S005,Brian Kamau,brian.kamau@email.com,C002,2024-04-15,Data Science,Technology,10,130000
5,S006,Lucy Wanjiru,lucy.wanjiru@email.com,C004,2024-05-02,Graphic Design,Design,8,100000
6,S007,David Kiptoo,david.kiptoo@email.com,C001,2024-06-10,Software Engineering,Technology,12,150000
7,S008,Naomi Wambui,naomi.wambui@email.com,C003,2024-06-25,Digital Marketing,Business,6,80000
8,S009,Peter Njoroge,peter.njoroge@email.com,C004,2024-07-01,Graphic Design,Design,8,100000
9,S010,Esther Chebet,esther.chebet@email.com,C002,2024-07-18,Data Science,Technology,10,130000

In [15]:
student_courses.to_csv('Student Courses.csv', index = False)

In [17]:
left = pd.merge(df_students, df_courses, on = 'CourseID', how = 'left')
left

,StudentID,FullName,Email,CourseID,JoinDate,CourseName,Department,DurationMonths,Fee
0,S001,James Mwangi,james.mwangi@email.com,C001,2024-02-10,Software Engineering,Technology,12,150000
1,S002,Faith Njeri,faith.njeri@email.com,C002,2024-03-12,Data Science,Technology,10,130000
2,S003,Kevin Otieno,kevin.otieno@email.com,C001,2024-03-20,Software Engineering,Technology,12,150000
3,S004,Susan Achieng,susan.achieng@email.com,C003,2024-04-01,Digital Marketing,Business,6,80000
4,S005,Brian Kamau,brian.kamau@email.com,C002,2024-04-15,Data Science,Technology,10,130000
5,S006,Lucy Wanjiru,lucy.wanjiru@email.com,C004,2024-05-02,Graphic Design,Design,8,100000
6,S007,David Kiptoo,david.kiptoo@email.com,C001,2024-06-10,Software Engineering,Technology,12,150000
7,S008,Naomi Wambui,naomi.wambui@email.com,C003,2024-06-25,Digital Marketing,Business,6,80000
8,S009,Peter Njoroge,peter.njoroge@email.com,C004,2024-07-01,Graphic Design,Design,8,100000
9,S010,Esther Chebet,esther.chebet@email.com,C002,2024-07-18,Data Science,Technology,10,130000

In [21]:
right = pd.merge(df_students, df_courses, on = 'CourseID', how = 'right')
right

,StudentID,FullName,Email,CourseID,JoinDate,CourseName,Department,DurationMonths,Fee
0,S001,James Mwangi,james.mwangi@email.com,C001,2024-02-10,Software Engineering,Technology,12,150000
1,S003,Kevin Otieno,kevin.otieno@email.com,C001,2024-03-20,Software Engineering,Technology,12,150000
2,S007,David Kiptoo,david.kiptoo@email.com,C001,2024-06-10,Software Engineering,Technology,12,150000
3,S002,Faith Njeri,faith.njeri@email.com,C002,2024-03-12,Data Science,Technology,10,130000
4,S005,Brian Kamau,brian.kamau@email.com,C002,2024-04-15,Data Science,Technology,10,130000
5,S010,Esther Chebet,esther.chebet@email.com,C002,2024-07-18,Data Science,Technology,10,130000
6,S004,Susan Achieng,susan.achieng@email.com,C003,2024-04-01,Digital Marketing,Business,6,80000
7,S008,Naomi Wambui,naomi.wambui@email.com,C003,2024-06-25,Digital Marketing,Business,6,80000
8,S006,Lucy Wanjiru,lucy.wanjiru@email.com,C004,2024-05-02,Graphic Design,Design,8,100000
9,S009,Peter Njoroge,peter.njoroge@email.com,C004,2024-07-01,Graphic Design,Design,8,100000

In [ ]:
from ta